# Generated by Django 5.1.4 on 2024-12-13 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travelers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('summary', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.PositiveSmallIntegerField(default=1)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelers.traveler')),
            ],
        ),
    ]
